#!/usr/bin/env tsx
import { promises as fs } from 'node:fs'
import path from 'node:path'
import chroma from 'chroma-js'
import type { BrandJson } from '../src/lib/brand/types'
import type { DesignJson } from '../src/lib/theme/types'

/**
 * Helper: Convert a hex color to HSL space-separated token (e.g., "220 75% 50%")
 * without the hsl() wrapper.
 */
function toHslTokens(hex: string, fallback = '220 10% 50%'): string {
  try {
    const [h, s, l] = chroma(hex).hsl()
    if (isNaN(h)) {
      // Achromatic color (grayscale) — use hue=0, keep saturation/lightness
      return `0 0% ${(l * 100).toFixed(0)}%`
    }
    return `${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`
  } catch {
    return fallback
  }
}

/**
 * Helper: Pick foreground color (near-white or near-black) with WCAG contrast ratio >= 4.5
 */
function pickForeground(
  bgHex: string,
  nearWhiteHex: string,
  nearBlackHex: string
): string {
  try {
    const cw = chroma.contrast(bgHex, nearWhiteHex)
    const cb = chroma.contrast(bgHex, nearBlackHex)
    if (cw >= 4.5) return nearWhiteHex
    if (cb >= 4.5) return nearBlackHex
    return cw >= cb ? nearWhiteHex : nearBlackHex
  } catch {
    return nearWhiteHex
  }
}

/**
 * Helper: Lighten a color by adjusting L channel (0-100)
 */
function lighten(hex: string, targetL: number): string {
  try {
    const [h, s] = chroma(hex).hsl()
    if (isNaN(h)) {
      // Achromatic — just use HSL with the target L
      return chroma([h, s * 100, targetL]).hex()
    }
    return chroma([h, s, targetL / 100]).hex()
  } catch {
    return '#f0f0f0'
  }
}

/**
 * Helper: Darken a color by adjusting L channel
 */
function darken(hex: string, targetL: number): string {
  try {
    const [h, s] = chroma(hex).hsl()
    if (isNaN(h)) {
      return chroma([h, s * 100, targetL]).hex()
    }
    return chroma([h, s, targetL / 100]).hex()
  } catch {
    return '#999999'
  }
}

async function main() {
  try {
    // 1. Read brand.json and design.json
    const brandPath = path.join(process.cwd(), 'content', 'brand.json')
    const designPath = path.join(process.cwd(), 'content', 'design.json')

    const brandJson = JSON.parse(
      await fs.readFile(brandPath, 'utf-8')
    ) as BrandJson
    const designJson = JSON.parse(
      await fs.readFile(designPath, 'utf-8')
    ) as DesignJson

    const {
      palette,
      firm: { name: firmName },
    } = brandJson
    const { typography, spacing, radius } = designJson

    // 2. Build palette → shadcn semantic mapping
    const primaryFg = pickForeground(
      palette.primary,
      palette.nearWhite,
      palette.nearBlack
    )
    const secondaryFg = pickForeground(
      palette.secondary,
      palette.nearWhite,
      palette.nearBlack
    )
    const accentFg = pickForeground(
      palette.complementary,
      palette.nearWhite,
      palette.nearBlack
    )

    // Derive muted colors
    const mutedForeground = lighten(palette.nearBlack, 40) // ~40% L
    const muted = darken(palette.nearWhite, 95) // ~95% L

    // Light gray for border + input
    const borderColor = darken(palette.nearWhite, 90) // ~90% L

    // Static red for destructive
    const destructive = chroma([0, 0.84, 0.6]).hex()

    // 3. Build the @theme CSS block
    const themeCss = `/* This file is generated by scripts/generate-theme.ts.
 * Edit brand.json / design.json and rerun the script instead of editing this file. */

@theme {
  /* Palette → shadcn semantic CSS variables (HSL space-separated) */
  --color-primary: ${toHslTokens(palette.primary)};
  --color-primary-foreground: ${toHslTokens(primaryFg)};
  --color-secondary: ${toHslTokens(palette.secondary)};
  --color-secondary-foreground: ${toHslTokens(secondaryFg)};
  --color-accent: ${toHslTokens(palette.complementary)};
  --color-accent-foreground: ${toHslTokens(accentFg)};
  --color-background: ${toHslTokens(palette.nearWhite)};
  --color-foreground: ${toHslTokens(palette.nearBlack)};
  --color-muted: ${toHslTokens(muted)};
  --color-muted-foreground: ${toHslTokens(mutedForeground)};
  --color-card: ${toHslTokens(palette.nearWhite)};
  --color-card-foreground: ${toHslTokens(palette.nearBlack)};
  --color-popover: ${toHslTokens(palette.nearWhite)};
  --color-popover-foreground: ${toHslTokens(palette.nearBlack)};
  --color-border: ${toHslTokens(borderColor)};
  --color-input: ${toHslTokens(borderColor)};
  --color-ring: ${toHslTokens(palette.action)};
  --color-destructive: ${toHslTokens(destructive)};
  --color-destructive-foreground: ${toHslTokens(palette.nearWhite)};

  /* Custom brand tokens — used directly by block components via var() */
  --color-action: ${palette.action};
  --color-action-foreground: ${palette.nearWhite};
  --color-primary-hex: ${palette.primary};
  --color-near-black: ${palette.nearBlack};
  --color-near-white: ${palette.nearWhite};
  --color-complementary: ${palette.complementary};

  /* Spacing scale (from design.json) — Tailwind v4 spacing tokens */
  --spacing-xs: ${spacing.xs};
  --spacing-sm: ${spacing.sm};
  --spacing-md: ${spacing.md};
  --spacing-lg: ${spacing.lg};
  --spacing-xl: ${spacing.xl};
  --spacing-2xl: ${spacing['2xl']};

  /* Radius (from design.json) */
  --radius-none: ${radius.none};
  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-pill: ${radius.pill};
  --radius: var(--radius-lg);

  /* Font family CSS vars — next/font sets these at runtime via className,
   * but we expose semantic names here so components can reference them */
  --font-heading: var(--font-heading-loaded, system-ui, sans-serif);
  --font-body: var(--font-body-loaded, system-ui, sans-serif);
}

:root {
  /* Duplicate in :root for shadcn components that read vars directly */
  --color-primary: ${toHslTokens(palette.primary)};
  --color-primary-foreground: ${toHslTokens(primaryFg)};
  --color-secondary: ${toHslTokens(palette.secondary)};
  --color-secondary-foreground: ${toHslTokens(secondaryFg)};
  --color-accent: ${toHslTokens(palette.complementary)};
  --color-accent-foreground: ${toHslTokens(accentFg)};
  --color-background: ${toHslTokens(palette.nearWhite)};
  --color-foreground: ${toHslTokens(palette.nearBlack)};
  --color-muted: ${toHslTokens(muted)};
  --color-muted-foreground: ${toHslTokens(mutedForeground)};
  --color-card: ${toHslTokens(palette.nearWhite)};
  --color-card-foreground: ${toHslTokens(palette.nearBlack)};
  --color-popover: ${toHslTokens(palette.nearWhite)};
  --color-popover-foreground: ${toHslTokens(palette.nearBlack)};
  --color-border: ${toHslTokens(borderColor)};
  --color-input: ${toHslTokens(borderColor)};
  --color-ring: ${toHslTokens(palette.action)};
  --color-destructive: ${toHslTokens(destructive)};
  --color-destructive-foreground: ${toHslTokens(palette.nearWhite)};

  /* Custom brand tokens */
  --color-action: ${palette.action};
  --color-action-foreground: ${palette.nearWhite};
  --color-primary-hex: ${palette.primary};
  --color-near-black: ${palette.nearBlack};
  --color-near-white: ${palette.nearWhite};
  --color-complementary: ${palette.complementary};

  /* Spacing scale */
  --spacing-xs: ${spacing.xs};
  --spacing-sm: ${spacing.sm};
  --spacing-md: ${spacing.md};
  --spacing-lg: ${spacing.lg};
  --spacing-xl: ${spacing.xl};
  --spacing-2xl: ${spacing['2xl']};

  /* Radius */
  --radius-none: ${radius.none};
  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-pill: ${radius.pill};
  --radius: var(--radius-lg);

  /* Font family */
  --font-heading: var(--font-heading-loaded, system-ui, sans-serif);
  --font-body: var(--font-body-loaded, system-ui, sans-serif);
}
`

    // 4. Write to src/styles/theme.css
    const themeCssPath = path.join(
      process.cwd(),
      'src',
      'styles',
      'theme.css'
    )
    await fs.mkdir(path.dirname(themeCssPath), { recursive: true })
    await fs.writeFile(themeCssPath, themeCss, 'utf-8')

    // 5. Print confirmation
    console.log(
      `✓ Wrote ${themeCssPath} (palette: ${palette.primary}, fonts: ${typography.headingFont} + ${typography.bodyFont})`
    )
  } catch (err) {
    console.error('Error generating theme.css:', err)
    process.exit(1)
  }
}

main()
