#!/usr/bin/env tsx
import { promises as fs } from 'node:fs'
import path from 'node:path'
import chroma from 'chroma-js'
import type { BrandJson } from '../src/lib/brand/types'
import type { DesignJson } from '../src/lib/theme/types'

/**
 * Helper: Convert a hex color to HSL space-separated token (e.g., "220 75% 50%")
 * without the hsl() wrapper.
 */
function toHslTokens(hex: string, fallback = '220 10% 50%'): string {
  try {
    const [h, s, l] = chroma(hex).hsl()
    if (isNaN(h)) {
      // Achromatic color (grayscale) — use hue=0, keep saturation/lightness
      return `0 0% ${(l * 100).toFixed(0)}%`
    }
    return `${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`
  } catch {
    return fallback
  }
}

/**
 * Helper: Pick foreground color (near-white or near-black) with WCAG contrast ratio >= 4.5
 */
function pickForeground(
  bgHex: string,
  nearWhiteHex: string,
  nearBlackHex: string
): string {
  try {
    const cw = chroma.contrast(bgHex, nearWhiteHex)
    const cb = chroma.contrast(bgHex, nearBlackHex)
    if (cw >= 4.5) return nearWhiteHex
    if (cb >= 4.5) return nearBlackHex
    return cw >= cb ? nearWhiteHex : nearBlackHex
  } catch {
    return nearWhiteHex
  }
}

/**
 * Helper: Override the HSL lightness of a color. `targetL` is 0–100.
 * Preserves the original hue and saturation. Uses chroma's `.set('hsl.l', ...)`
 * to avoid the bare-array constructor which defaults to RGB.
 */
function setLightness(hex: string, targetL: number): string {
  try {
    return chroma(hex).set('hsl.l', targetL / 100).hex()
  } catch {
    return hex
  }
}

async function main() {
  try {
    // 1. Read brand.json and design.json
    const brandPath = path.join(process.cwd(), 'content', 'brand.json')
    const designPath = path.join(process.cwd(), 'content', 'design.json')

    const brandJson = JSON.parse(
      await fs.readFile(brandPath, 'utf-8')
    ) as BrandJson
    const designJson = JSON.parse(
      await fs.readFile(designPath, 'utf-8')
    ) as DesignJson

    const {
      palette,
      firm: { name: firmName },
    } = brandJson
    const { typography, spacing, radius } = designJson

    // 2. Build palette → shadcn semantic mapping
    const primaryFg = pickForeground(
      palette.primary,
      palette.nearWhite,
      palette.nearBlack
    )
    const secondaryFg = pickForeground(
      palette.secondary,
      palette.nearWhite,
      palette.nearBlack
    )
    const accentFg = pickForeground(
      palette.complementary,
      palette.nearWhite,
      palette.nearBlack
    )

    // Derive muted colors. nearBlack → ~40% L gives a mid-gray for body-secondary
    // text. nearWhite → ~95% L gives an off-white muted surface. nearWhite →
    // ~90% L gives a light-gray border.
    const mutedForeground = setLightness(palette.nearBlack, 40)
    const muted = setLightness(palette.nearWhite, 95)
    const borderColor = setLightness(palette.nearWhite, 90)

    // Static red for destructive. Use chroma's HSL constructor explicitly so
    // the bare-array doesn't get treated as RGB.
    const destructive = chroma.hsl(0, 0.84, 0.6).hex()

    // 3. Build the @theme CSS block
    const themeCss = `/* This file is generated by scripts/generate-theme.ts.
 * Edit brand.json / design.json and rerun the script instead of editing this file. */

@theme {
  /* Palette → shadcn semantic CSS variables (HSL space-separated) */
  --color-primary: hsl(${toHslTokens(palette.primary)});
  --color-primary-foreground: hsl(${toHslTokens(primaryFg)});
  --color-secondary: hsl(${toHslTokens(palette.secondary)});
  --color-secondary-foreground: hsl(${toHslTokens(secondaryFg)});
  --color-accent: hsl(${toHslTokens(palette.complementary)});
  --color-accent-foreground: hsl(${toHslTokens(accentFg)});
  --color-background: hsl(${toHslTokens(palette.nearWhite)});
  --color-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-muted: hsl(${toHslTokens(muted)});
  --color-muted-foreground: hsl(${toHslTokens(mutedForeground)});
  --color-card: hsl(${toHslTokens(palette.nearWhite)});
  --color-card-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-popover: hsl(${toHslTokens(palette.nearWhite)});
  --color-popover-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-border: hsl(${toHslTokens(borderColor)});
  --color-input: hsl(${toHslTokens(borderColor)});
  --color-ring: hsl(${toHslTokens(palette.action)});
  --color-destructive: hsl(${toHslTokens(destructive)});
  --color-destructive-foreground: hsl(${toHslTokens(palette.nearWhite)});

  /* Custom brand tokens — used directly by block components via var() */
  --color-action: ${palette.action};
  --color-action-foreground: ${palette.nearWhite};
  --color-primary-hex: ${palette.primary};
  --color-near-black: ${palette.nearBlack};
  --color-near-white: ${palette.nearWhite};
  --color-complementary: ${palette.complementary};

  /* Spacing scale — exposed under a c5-prefixed namespace to avoid
   * colliding with Tailwind v4's --spacing-* namespace, which feeds
   * max-w-*, w-*, h-*, p-*, m-*, gap-* utilities. Naming these tokens
   * spacing-xs/sm/md/lg/xl/2xl would silently override max-w-2xl etc.
   * Reference these in custom CSS via var(--c5-space-xs). For Tailwind
   * utility values, use the native scale (p-1=4px, p-2=8px, p-4=16px,
   * p-6=24px, p-12=48px, p-24=96px). */
  --c5-space-xs: ${spacing.xs};
  --c5-space-sm: ${spacing.sm};
  --c5-space-md: ${spacing.md};
  --c5-space-lg: ${spacing.lg};
  --c5-space-xl: ${spacing.xl};
  --c5-space-2xl: ${spacing['2xl']};

  /* Radius (from design.json) */
  --radius-none: ${radius.none};
  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-pill: ${radius.pill};
  --radius: var(--radius-lg);

  /* Font family CSS vars — next/font sets these at runtime via className,
   * but we expose semantic names here so components can reference them */
  --font-heading: var(--font-heading-loaded, system-ui, sans-serif);
  --font-body: var(--font-body-loaded, system-ui, sans-serif);
}

:root {
  /* Duplicate in :root for shadcn components that read vars directly */
  --color-primary: hsl(${toHslTokens(palette.primary)});
  --color-primary-foreground: hsl(${toHslTokens(primaryFg)});
  --color-secondary: hsl(${toHslTokens(palette.secondary)});
  --color-secondary-foreground: hsl(${toHslTokens(secondaryFg)});
  --color-accent: hsl(${toHslTokens(palette.complementary)});
  --color-accent-foreground: hsl(${toHslTokens(accentFg)});
  --color-background: hsl(${toHslTokens(palette.nearWhite)});
  --color-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-muted: hsl(${toHslTokens(muted)});
  --color-muted-foreground: hsl(${toHslTokens(mutedForeground)});
  --color-card: hsl(${toHslTokens(palette.nearWhite)});
  --color-card-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-popover: hsl(${toHslTokens(palette.nearWhite)});
  --color-popover-foreground: hsl(${toHslTokens(palette.nearBlack)});
  --color-border: hsl(${toHslTokens(borderColor)});
  --color-input: hsl(${toHslTokens(borderColor)});
  --color-ring: hsl(${toHslTokens(palette.action)});
  --color-destructive: hsl(${toHslTokens(destructive)});
  --color-destructive-foreground: hsl(${toHslTokens(palette.nearWhite)});

  /* Custom brand tokens */
  --color-action: ${palette.action};
  --color-action-foreground: ${palette.nearWhite};
  --color-primary-hex: ${palette.primary};
  --color-near-black: ${palette.nearBlack};
  --color-near-white: ${palette.nearWhite};
  --color-complementary: ${palette.complementary};

  /* Spacing scale (c5-prefixed to avoid Tailwind --spacing-* collision) */
  --c5-space-xs: ${spacing.xs};
  --c5-space-sm: ${spacing.sm};
  --c5-space-md: ${spacing.md};
  --c5-space-lg: ${spacing.lg};
  --c5-space-xl: ${spacing.xl};
  --c5-space-2xl: ${spacing['2xl']};

  /* Radius */
  --radius-none: ${radius.none};
  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-pill: ${radius.pill};
  --radius: var(--radius-lg);

  /* Font family */
  --font-heading: var(--font-heading-loaded, system-ui, sans-serif);
  --font-body: var(--font-body-loaded, system-ui, sans-serif);
}
`

    // 4. Write to src/styles/theme.css
    const themeCssPath = path.join(
      process.cwd(),
      'src',
      'styles',
      'theme.css'
    )
    await fs.mkdir(path.dirname(themeCssPath), { recursive: true })
    await fs.writeFile(themeCssPath, themeCss, 'utf-8')

    // 5. Print confirmation
    console.log(
      `✓ Wrote ${themeCssPath} (palette: ${palette.primary}, fonts: ${typography.headingFont} + ${typography.bodyFont})`
    )
  } catch (err) {
    console.error('Error generating theme.css:', err)
    process.exit(1)
  }
}

main()
